apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Dto/MessageDto/MessageDto.java

Fix MessageController #4

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Entity/GameRoom.java
apps/server/src/main/java/org/gamza/server/Entity/Message.java
apps/server/src/main/java/org/gamza/server/Repository/RoomRepository.java
apps/server/src/main/java/org/gamza/server/Service/RoomService.java

Fix MessageController #7

---

apps/server/src/main/java/org/gamza/server/Repository/RoomRepository.java
apps/server/src/main/java/org/gamza/server/Service/RoomService.java

- fix fetch join to entity graph

Fix MessageController #8

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

- Cause IndexOutOfBoundsException

Fix MessageController

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Service/User/UserService.java

- parameter change to nickname

Fix update ready/team status code #2

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

Fix RestTemplate for START test #2

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

Fix RestTemplate for START test #3

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

- fix code (toString -> toJSONString)

Fix RestTemplate for START test #4

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

- fix code (teamStatus toString)

Fix RestTemplate for START test #5

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

Fix RestTemplate for START test #6

---

apps/server/src/main/java/org/gamza/server/Controller/GameController.java
apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

Fix RestTemplate for START test #7

---

apps/server/src/main/java/org/gamza/server/Config/SecurityConfig.java
apps/server/src/main/java/org/gamza/server/Controller/GameController.java

Fix SecurityConfig for START test

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java
apps/server/src/main/java/org/gamza/server/Service/RoomService.java

- Create component for EventListener

Fix DisconnectListener #1

---

apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java

- Get header info and print to console

Fix DisconnectListener #2

---

apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java
apps/server/src/main/java/org/gamza/server/Service/RoomService.java

- Fix DisconnectListener code logic

Fix DisconnectListener #3

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java
apps/server/src/main/java/org/gamza/server/Service/User/UserService.java

- Fix DisconnectListener's update user status

Fix DisconnectListener #4

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Entity/Message.java

- Fix update message's room for user status

Fix MessageController #1

---

apps/server/src/main/java/org/gamza/server/Error/ErrorCode.java
apps/server/src/main/java/org/gamza/server/Error/Exception/DuplicateException.java
apps/server/src/main/java/org/gamza/server/Service/AuthService.java
apps/server/src/main/java/org/gamza/server/Service/RoomService.java

- Add ErrorCode for Duplicate entry key

Add ErrorCode for SQLIntegrityConstraintViolationException

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java

- Update EventListener's room data in message

Fix DisconnectEventListener

---

apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java

Update EventListener's room data in message #2

Fix DisconnectEventListener #2

---

apps/client/example.env
apps/client/src/constants/setting.ts
apps/client/src/containers/GameRoomPage/GameRoomPage.tsx
apps/client/src/containers/IntroPage/IntroPage.tsx
apps/client/src/containers/SignUpPage/SignUpPage.tsx
apps/client/src/hooks/useChatWebSocket.ts
apps/client/src/hooks/useRoomWebSocket.ts
apps/client/src/util/axios.ts

feat. env설정

---

apps/server/src/main/java/org/gamza/server/Service/RoomService.java

비번방 검증 로직 수정

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java
apps/server/src/main/java/org/gamza/server/Service/MessageService.java

방 입장시 유저 업데이트 안되는 현상 및 게임 시작시 에러 발생 수정

JOIN, START Bug fix

---

apps/server/src/main/java/org/gamza/server/Controller/AuthController.java
apps/server/src/main/java/org/gamza/server/Controller/GameController.java
apps/server/src/main/java/org/gamza/server/Dto/GameDto/GameRequestDto.java
apps/server/src/main/java/org/gamza/server/Dto/UserDto/UserRecordDto.java
apps/server/src/main/java/org/gamza/server/Entity/RecordResult.java
apps/server/src/main/java/org/gamza/server/Service/GameService.java
apps/server/src/main/java/org/gamza/server/Service/MessageService.java
apps/server/src/main/java/org/gamza/server/Service/User/UserService.java

ResultRecord 관련 DTO 구조 수정 및 서비스 추가

게임 시작과 종료에 따른 수정 및 추가

---

apps/server/src/main/java/org/gamza/server/Service/MessageService.java

Join 요청 코드 수정

---

apps/client/src/containers/GameRoomPage/components/Client.tsx
apps/client/src/containers/GameRoomPage/components/UserCard.tsx
apps/client/src/containers/LobbyPage/components/Info.tsx
apps/client/src/containers/LobbyPage/modal/WatchUserInfoModal.tsx
apps/client/src/hooks/useLobbyData.ts
apps/client/src/hooks/useRoomWebSocket.ts

chore. READY 리턴 값 boolean 형식으로 변경함에 따라 코드 수정
delete. refetchInterval 기능 삭제 #129

feat. 방장 처리 구현, 전적 정보 구현 #135 #139

---

apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java

방 나가기 에러 수정 - 1

---

apps/server/src/main/java/org/gamza/server/Controller/MessageEventListener.java

방 나가기 에러 수정 - 2

---

apps/server/src/main/java/org/gamza/server/Service/MessageService.java
apps/server/src/main/java/org/gamza/server/Service/RoomService.java

방 나가기 에러 수정 - 3
- SQL Deadlock 에러

방 나가기 에러 수정 - 3

---

apps/client/src/containers/GameRoomPage/components/Map.tsx
apps/client/src/containers/LobbyPage/components/Info.tsx
apps/client/src/containers/LobbyPage/components/Search.tsx
apps/client/src/containers/LobbyPage/components/Tool.tsx
apps/client/src/containers/LobbyPage/modal/WatchUserInfoModal.tsx
apps/client/src/containers/SignUpPage/SignUpPage.tsx

미구현 기능들 주석처리

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

- MessageController에 try catch 추가

유령방 에러 수정 - 3

---

apps/server/src/main/java/org/gamza/server/Controller/MessageController.java

유저 가득 찬 방 에러 수정

---

apps/server/src/main/java/org/gamza/server/Controller/RoomController.java
apps/server/src/main/java/org/gamza/server/Service/RoomService.java

방 입장 검증 API 추가
